apiVersion: v1
kind: ConfigMap
metadata:
  name: request-dispatch-config
data:
  traefik-dynamic-conf.yml: |
    http:
      middlewares:
        request-dispatch:
          plugin:
            request-dispatch:
              logLevel: {{ .Values.requestDispatch.logLevel }}
              markHeader: {{ .Values.requestDispatch.markHeader }}
              markHosts:
                alpha:
                  {{- range .Values.requestDispatch.markHosts.alpha }}
                  - {{ . }}
                  {{- end }}
                beta:
                  {{- range .Values.requestDispatch.markHosts.beta }}
                  - {{ . }}
                  {{- end }}